// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type BanHistory struct {
	ID        int32      `db:"id" json:"id"`
	UserID    *int       `db:"user_id" json:"user_id"`
	Reason    *string    `db:"reason" json:"reason"`
	CreatedAt *time.Time `db:"created_at" json:"created_at"`
}

type Post struct {
	ID        int32      `db:"id" json:"id"`
	UserID    *int       `db:"user_id" json:"user_id"`
	Title     string     `db:"title" json:"title"`
	Content   *string    `db:"content" json:"content"`
	Images    []string   `db:"images" json:"images"`
	CreatedAt *time.Time `db:"created_at" json:"created_at"`
	DeletedAt *time.Time `db:"deleted_at" json:"deleted_at"`
	UpdatedAt *time.Time `db:"updated_at" json:"updated_at"`
}

type Profile struct {
	ID        int32      `db:"id" json:"id"`
	UserID    *int       `db:"user_id" json:"user_id"`
	Bio       *string    `db:"bio" json:"bio"`
	PhotoUrl  *string    `db:"photo_url" json:"photo_url"`
	CreatedAt *time.Time `db:"created_at" json:"created_at"`
	UpdatedAt *time.Time `db:"updated_at" json:"updated_at"`
}

type User struct {
	ID        int32       `db:"id" json:"id"`
	FullName  string      `db:"full_name" json:"full_name"`
	Username  string      `db:"username" json:"username"`
	Password  string      `db:"password" json:"password"`
	Stage     int         `db:"stage" json:"stage"`
	Banned    pgtype.Bool `db:"banned" json:"banned"`
	CreatedAt *time.Time  `db:"created_at" json:"created_at"`
	DeletedAt *time.Time  `db:"deleted_at" json:"deleted_at"`
	UpdatedAt *time.Time  `db:"updated_at" json:"updated_at"`
}
