// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Post struct {
	ID        int32
	UserID    pgtype.Int4
	Title     string
	Content   pgtype.Text
	Images    []string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Profile struct {
	ID        int32
	UserID    pgtype.Int4
	Bio       pgtype.Text
	PhotoUrl  pgtype.Text
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type User struct {
	ID        int32
	FullName  string
	Username  string
	Password  string
	Stage     int32
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
