// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: posts.sql

package sqlc

import (
	"context"
)

const createPost = `-- name: CreatePost :exec
INSERT INTO posts (user_id, title, content, images)
VALUES ($1, $2, $3, $4)
`

type CreatePostParams struct {
	UserID  *int     `db:"user_id" json:"user_id"`
	Title   string   `db:"title" json:"title"`
	Content *string  `db:"content" json:"content"`
	Images  []string `db:"images" json:"images"`
}

// Creates a new post
func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) error {
	_, err := q.db.Exec(ctx, createPost,
		arg.UserID,
		arg.Title,
		arg.Content,
		arg.Images,
	)
	return err
}

const getPosts = `-- name: GetPosts :many
SELECT id, user_id, title, content, images, created_at, deleted_at, updated_at FROM posts
WHERE (title ILIKE $3 OR content ILIKE $3)
ORDER BY id DESC
LIMIT $1 OFFSET $2
`

type GetPostsParams struct {
	Limit  int    `db:"limit" json:"limit"`
	Offset int    `db:"offset" json:"offset"`
	Search string `db:"search" json:"search"`
}

// Returns all posts for a given user
func (q *Queries) GetPosts(ctx context.Context, arg GetPostsParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, getPosts, arg.Limit, arg.Offset, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Content,
			&i.Images,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostsCount = `-- name: GetPostsCount :one
SELECT COUNT(*) FROM posts
WHERE (title ILIKE $1 OR content ILIKE $1)
`

// Returns the count of posts for a given user
func (q *Queries) GetPostsCount(ctx context.Context, search string) (int64, error) {
	row := q.db.QueryRow(ctx, getPostsCount, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserPosts = `-- name: GetUserPosts :many
SELECT id, user_id, title, content, images, created_at, deleted_at, updated_at FROM posts
WHERE user_id = $3
AND (title ILIKE $4 OR content ILIKE $4)
ORDER BY id DESC
LIMIT $1 OFFSET $2
`

type GetUserPostsParams struct {
	Limit  int    `db:"limit" json:"limit"`
	Offset int    `db:"offset" json:"offset"`
	UserID *int   `db:"user_id" json:"user_id"`
	Search string `db:"search" json:"search"`
}

// Returns all posts for a given user
func (q *Queries) GetUserPosts(ctx context.Context, arg GetUserPostsParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, getUserPosts,
		arg.Limit,
		arg.Offset,
		arg.UserID,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Content,
			&i.Images,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserPostsCount = `-- name: GetUserPostsCount :one
SELECT COUNT(*) FROM posts WHERE user_id = $1
AND (title ILIKE $2 OR content ILIKE $2)
`

type GetUserPostsCountParams struct {
	UserID *int   `db:"user_id" json:"user_id"`
	Search string `db:"search" json:"search"`
}

// Returns the count of posts for a given user
func (q *Queries) GetUserPostsCount(ctx context.Context, arg GetUserPostsCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, getUserPostsCount, arg.UserID, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}
