// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (full_name, username, password, stage)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateUserParams struct {
	FullName string
	Username string
	Password string
	Stage    int32
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int32, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.FullName,
		arg.Username,
		arg.Password,
		arg.Stage,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
