// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ban_history.sql

package sqlc

import (
	"context"
)

const getBanHistory = `-- name: GetBanHistory :many
SELECT id, user_id, reason, created_at
FROM ban_history
WHERE user_id = $1
`

// Get ban history for a user
func (q *Queries) GetBanHistory(ctx context.Context, userID *int) ([]BanHistory, error) {
	rows, err := q.db.Query(ctx, getBanHistory, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BanHistory{}
	for rows.Next() {
		var i BanHistory
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
