name: students-archive-data
services:
  redis:
    image: redis:7.4-alpine
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass studentsarchive123456 --appendonly yes
    volumes:
      - redis_data:/data

  db:
    image: postgres:17-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: students-archive
      POSTGRES_PASSWORD: studentsarchive123456
      POSTGRES_DB: students-archive
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U students-archive -d students-archive"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis_data:
    driver: local
  postgres_data:
